/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.InsumoBL;
import Modelo.Insumo;
import Modelo.unidadMed;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian
 */
public class JFBuscarInsumo extends javax.swing.JDialog {

    /**
     * Creates new form JFBuscarInsumo
     */
    private ArrayList<Insumo> listaInsumo;
    private ArrayList<Insumo> listaFiltrada;
    private InsumoBL logicaNegocio;
    private Insumo insumoSeleccionado;
    
    public JFBuscarInsumo(JDialog d, Boolean b) {
        super(d,b);
        initComponents();
        
        logicaNegocio = new InsumoBL();
        listaInsumo = logicaNegocio.listarInsumo();
        DefaultTableModel aux= (DefaultTableModel) jTable1.getModel();
        Object [] fila = new Object [3];
        unidadMed um;
         for(int i=0;i<listaInsumo.size();i++){
            fila[0] = listaInsumo.get(i).getidInsumo();
            fila[1] = listaInsumo.get(i).getNombre();
            um = listaInsumo.get(i).getunidMed();
            if(um == unidadMed.kg) fila[2] = "KILOGRAMOS";
            else if(um == unidadMed.cajas) fila[2] = "CAJAS";
            else if(um == unidadMed.lt) fila[2] = "LITROS";
            else if(um == unidadMed.unid) fila[2] = "UNIDADES";            
            aux.addRow(fila);
        }
    }
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonBuscar = new javax.swing.JToggleButton();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        buttonSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datos de Insumo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Unidad de Medida"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        labelNombre.setText("Nombre");

        buttonSeleccionar.setText("Seleccionar");
        buttonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addGap(84, 84, 84)
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSeleccionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar)
                    .addComponent(buttonSeleccionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        // TODO add your handling code here:
        String filtro =  textNombre.getText().toLowerCase();
        listaFiltrada = new ArrayList<Insumo>();
        for (int i = 0; i < listaInsumo.size(); i++) {
            if(listaInsumo.get(i).getNombre().toLowerCase().contains(filtro)){
                listaFiltrada.add(listaInsumo.get(i));
            }
        }
        
        DefaultTableModel aux= (DefaultTableModel) jTable1.getModel();
        aux.setRowCount(0);
        Object [] fila = new Object [3];
        unidadMed um;
        for(int i=0;i<listaFiltrada.size();i++){
            fila[0] = listaFiltrada.get(i).getidInsumo();
            fila[1] = listaFiltrada.get(i).getNombre();
            um = listaFiltrada.get(i).getunidMed();
            if(um == unidadMed.kg) fila[2] = "KILOGRAMOS";
            else if(um == unidadMed.cajas) fila[2] = "CAJAS";
            else if(um == unidadMed.lt) fila[2] = "LITROS";
            else if(um == unidadMed.unid) fila[2] = "UNIDADES";            
            aux.addRow(fila);
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeleccionarActionPerformed
        // TODO add your handling code here:
        try{
            insumoSeleccionado= new Insumo();
            if(textNombre.getText().isEmpty()){
                insumoSeleccionado=listaInsumo.get(jTable1.getSelectedRow());
            }
            else{
                insumoSeleccionado=listaFiltrada.get(jTable1.getSelectedRow());
            }            
            super.dispose();
        }catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_buttonSeleccionarActionPerformed
    
    public Insumo getinsumoSeleccionado(){
        return insumoSeleccionado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBuscarInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBuscarInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBuscarInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBuscarInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBuscarInsumo(null,false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonBuscar;
    private javax.swing.JButton buttonSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
