/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ClientesBL;
import Modelo.Empresa;
import Modelo.Natural;
import Modelo.Producto;
import java.awt.Dialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Kathy Ruiz :)
 */
public class JFBuscarCliente extends javax.swing.JDialog {

    private String tipo;
    private ClientesBL LogicaNegocio;
    private ArrayList<Natural> listaNatural;
    private ArrayList<Empresa> listaEmpresa;
    private Natural naturalSeleccionado;
    private Empresa empresaSeleccionada;

    /**
     * @return the naturalSeleccionado
     */
    public Natural getNaturalSeleccionado() {
        return naturalSeleccionado;
    }

    /**
     * @param naturalSeleccionado the naturalSeleccionado to set
     */
    public void setNaturalSeleccionado(Natural naturalSeleccionado) {
        this.naturalSeleccionado = naturalSeleccionado;
    }

    /**
     * @return the empresaSeleccionada
     */
    public Empresa getEmpresaSeleccionada() {
        return empresaSeleccionada;
    }

    /**
     * @param empresaSeleccionada the empresaSeleccionada to set
     */
    public void setEmpresaSeleccionada(Empresa empresaSeleccionada) {
        this.empresaSeleccionada = empresaSeleccionada;
    }

    /**
     * Creates new form JFBuscarCliente
     */
    public JFBuscarCliente(String tipo, Dialog f, boolean b) {
        super(f, b);
        initComponents();
        LogicaNegocio = new ClientesBL();
        listaEmpresa = new ArrayList<Empresa>(LogicaNegocio.listarEmpresa());
        listaNatural = new ArrayList<Natural>(LogicaNegocio.listarNatural());
        this.tipo = tipo;

        DefaultTableModel modelo = (DefaultTableModel) tableCliente.getModel();
        if (tipo == "Empresa") {
            modelo.addColumn("RUC");
            modelo.addColumn("RAZON SOCIAL");

            Object[] fila = new Object[2];
            for (int i = 0; i < listaEmpresa.size(); i++) {
                fila[0] = listaEmpresa.get(i).getRuc();
                fila[1] = listaEmpresa.get(i).getRazonSocial();
                modelo.addRow(fila);
            }

        } else {
            modelo.addColumn("DNI");
            modelo.addColumn("NOMBRE");

            Object[] fila = new Object[2];
            for (int i = 0; i < listaNatural.size(); i++) {
                fila[0] = listaNatural.get(i).getDNI();
                fila[1] = listaNatural.get(i).getNombre() + " " + listaNatural.get(i).getApellidos();
                modelo.addRow(fila);
            }
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //JFramePedidos.value=0;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCliente);

        jLabel1.setText("Tabla de Clientes:");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnSelect.setText("Seleccionar");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFiltrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelect)
                            .addGap(37, 37, 37)
                            .addComponent(btnCerrar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSelect)
                            .addComponent(btnCerrar))
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        //JFramePedidos.value=0;
        super.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        try {
            if (tipo == "Empresa") {
                setEmpresaSeleccionada(new Empresa());
                setEmpresaSeleccionada(listaEmpresa.get(tableCliente.getSelectedRow()));
            } else {
                setNaturalSeleccionado(new Natural());
                setNaturalSeleccionado(listaNatural.get(tableCliente.getSelectedRow()));
            }
            //JFramePedidos.value=2;
            super.dispose();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        String filtro = txtFiltro.getText().toLowerCase();
        if (tipo == "Empresa") {
            ArrayList<Empresa> listaFiltro = new ArrayList<Empresa>();
            for (int i = 0; i < listaEmpresa.size(); i++) {
                if (listaEmpresa.get(i).getRazonSocial().toLowerCase().contains(filtro)) {
                    listaFiltro.add(listaEmpresa.get(i));
                }
            }
            DefaultTableModel modelo = (DefaultTableModel) tableCliente.getModel();
            modelo.setRowCount(0);
            Object[] fila = new Object[2];
            for (int i = 0; i < listaFiltro.size(); i++) {
                //fila[0] = listaEmpleados.get(i).getID();
                fila[0] = listaFiltro.get(i).getRuc();
                fila[1] = listaFiltro.get(i).getRazonSocial();
                modelo.addRow(fila);
            }
        } else {
            ArrayList<Natural> listaFiltro = new ArrayList<Natural>();
            for (int i = 0; i < listaNatural.size(); i++) {
                if (listaNatural.get(i).getNombre().toLowerCase().contains(filtro) || listaNatural.get(i).getApellidos().toLowerCase().contains(filtro)) {
                    listaFiltro.add(listaNatural.get(i));
                }
            }
            DefaultTableModel modelo = (DefaultTableModel) tableCliente.getModel();
            modelo.setRowCount(0);
            Object[] fila = new Object[2];
            for (int i = 0; i < listaFiltro.size(); i++) {
                //fila[0] = listaEmpleados.get(i).getID();
                fila[0] = listaFiltro.get(i).getDNI();
                fila[1] = listaFiltro.get(i).getNombre() + " " + listaFiltro.get(i).getApellidos();
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //new JFBuscarCliente().setVisible(true);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
                //new JFBuscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
