/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DocumentoPagoBL;
import Modelo.Boleta;
import Modelo.Cliente;
import Modelo.DocumentoPago;
import Modelo.Factura;
import Modelo.Natural;
import java.awt.Dialog;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class JFBuscarDocumentosPago extends javax.swing.JDialog {

    private DocumentoPagoBL documentoPagoBL;
    private DocumentoPago documentoSeleccionado;
    private int idPedidoSeleccionado;
    ArrayList<Object> documentosConExtra;
    /**
     * Creates new form JFBuscarDocumentosPago
     */
    public JFBuscarDocumentosPago(Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initMyComponents();
    }
    
    public void initMyComponents(){
        documentoPagoBL = new DocumentoPagoBL();
        cargarTabla();
    }
    
    public void cargarTabla(){
        try{
            documentosConExtra = documentoPagoBL.listarDocumentosPagoYExtra();
            DefaultTableModel modelo = (DefaultTableModel)tablaDocsPago.getModel();
            Object[] fila = new Object[8]; //columnas: [0]NumDoc [1]TipoDoc [2]ID Pedido [3]FechaR [4]FechaE [5]Cli [6]tipoCli [7]Tot
            for(Object objTupla : documentosConExtra){
                //tupla: [0]=DocPago [1]=FechaRegistro [2]=FechaEntrega [3]=EstadoPedido
                Object[] tupla = (Object[]) objTupla;
                
                
                DocumentoPago documentoPago = (DocumentoPago)tupla[0];
                Cliente cliente = documentoPago.getcliente();
                String tipoDocPago;
                String tipoCliente;
                String nombreCliente;
//                int idDocCliente;
                
                if(cliente instanceof Natural){
                    tipoDocPago = "Boleta";
                    tipoCliente = "Natural";
                    nombreCliente = ((Boleta)documentoPago).getNombre();
//                    idDocCliente = ((Boleta)documentoPago).getDni();
                }else{
                    tipoDocPago = "Factura";
                    tipoCliente = "Empresa";
                    nombreCliente = ((Factura) documentoPago).getRazonSocial();
//                    idDocCliente = ((Factura) documentoPago).getRuc();
                    
                }
                
                Date fechaRegistro = (Date)tupla[1];
                Date fechaEntrega = (Date)tupla[2];
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                
                fila[0] = documentoPago.getidDoc();
                fila[1] = tipoDocPago;
                fila[2] = documentoPago.getidPedido();
                fila[3] = formatoFecha.format(fechaRegistro);
                fila[4] = formatoFecha.format(fechaEntrega);
                fila[5] = nombreCliente;
                fila[6] = tipoCliente;
                fila[7] = documentoPago.gettotal();
                
                modelo.addRow(fila);

            }
        }catch (Exception e){
            //System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocsPago = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaDocsPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Doc. Pago", "Tipo Doc. Pago", "ID Pedido", "Fecha Registro", "Fecha Entrega", "Cliente", "Tipo Cliente", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDocsPago);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSeleccionar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnSeleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        try{
            
            Object[] tupla = (Object[])documentosConExtra.get(tablaDocsPago.getSelectedRow());
            documentoSeleccionado =  (DocumentoPago)tupla[0];
            idPedidoSeleccionado = documentoSeleccionado.getidPedido();
            super.dispose();
            
        }catch (Exception e){
            //System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBuscarDocumentosPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBuscarDocumentosPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBuscarDocumentosPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBuscarDocumentosPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                JFBuscarDocumentosPago dialog = new JFBuscarDocumentosPago(null, true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
                dialog.setVisible(true);
                }catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDocsPago;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the documentoSeleccionado
     */
    public DocumentoPago getDocumentoSeleccionado() {
        return documentoSeleccionado;
    }

    /**
     * @param documentoSeleccionado the documentoSeleccionado to set
     */
    public void setDocumentoSeleccionado(DocumentoPago documentoSeleccionado) {
        this.documentoSeleccionado = documentoSeleccionado;
    }

    /**
     * @return the idPedidoSeleccionado
     */
    public int getIdPedidoSeleccionado() {
        return idPedidoSeleccionado;
    }

    /**
     * @param idPedidoSeleccionado the idPedidoSeleccionado to set
     */
    public void setIdPedidoSeleccionado(int idPedidoSeleccionado) {
        this.idPedidoSeleccionado = idPedidoSeleccionado;
    }
}
