package Vista;

import javax.swing.JDialog;

import Controlador.ProductoAdmiBL;
import Modelo.Producto;
import java.awt.Dialog;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/* @author C-bastian */
public class JFEliminarProducto extends javax.swing.JDialog{
    
    private ArrayList<Producto> listaProducto;
    private ArrayList<Producto> listaFiltrada;
    private ProductoAdmiBL logicaNegocio;
    private Producto productoSeleccionado;
    private int resultado=0;

    /**
     * Creates new form NewJFrame
     */
    public JFEliminarProducto(JDialog d, Boolean b) {
        super(d,b);
        initComponents();
        
        logicaNegocio = new ProductoAdmiBL();
        listaProducto = logicaNegocio.listarProductos();
        DefaultTableModel aux= (DefaultTableModel) jTable1.getModel();
        Object [] fila = new Object [2];
        for(int i=0;i<listaProducto.size();i++){
            fila[0] = listaProducto.get(i).getidProducto();
            fila[1] = listaProducto.get(i).getnombProducto();
            aux.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonSeleccionar = new javax.swing.JButton();
        buttonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tabla de Productos");

        buttonSeleccionar.setText("Seleccionar");
        buttonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeleccionarActionPerformed(evt);
            }
        });

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        labelNombre.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addGap(55, 55, 55)
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSeleccionar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSeleccionar)
                    .addComponent(buttonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeleccionarActionPerformed
        // TODO add your handling code here:
        try{
            productoSeleccionado= new Producto();
            if(textNombre.getText().isEmpty()){
                productoSeleccionado=listaProducto.get(jTable1.getSelectedRow());
            }
            else{
                productoSeleccionado=listaFiltrada.get(jTable1.getSelectedRow());
            }
            resultado= logicaNegocio.eliminarProducto(productoSeleccionado.getidProducto());
            super.dispose();
        }catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_buttonSeleccionarActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        // TODO add your handling code here:
        String filtro =  textNombre.getText().toLowerCase();
        listaFiltrada = new ArrayList<Producto>();
        for (int i = 0; i < listaProducto.size(); i++) {
            if(listaProducto.get(i).getnombProducto().toLowerCase().contains(filtro)){
                listaFiltrada.add(listaProducto.get(i));
            }
        }
        
        DefaultTableModel aux= (DefaultTableModel) jTable1.getModel();
        aux.setRowCount(0);
        Object [] fila = new Object [2];
        for(int i=0;i<listaFiltrada.size();i++){
            fila[0] = listaFiltrada.get(i).getidProducto();
            fila[1] = listaFiltrada.get(i).getnombProducto();
            aux.addRow(fila);
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    public int getResultado(){
        return resultado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
//        CREATE DEFINER=`inf282g7`@`%` PROCEDURE `LISTAR_INGREDIENTES_PRODUCTO_ADMI`(in id int)
//BEGIN
//	select i.idInsumo,i.Nombre,ig.Cantidad,i.UnidadDeMedida_idUnidadDeMedida
//    from Insumo i
//    inner join Producto p on p.idProducto = id
//    inner join IngredientesXProducto ip on ip.Producto_idProducto = p.idProducto
//    inner join Ingrediente ig on ig.idIngrediente = ip.Producto_idProducto;
//    
//    
//
//END

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFModificarProducto(null,false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
