/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.UsuarioBL;
import Modelo.*;
import java.util.ArrayList;
import java.util.Dictionary;
import java.awt.Image;
import java.awt.TextField;
import java.util.Map;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import Email.Email ;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Kathy Ruiz :)
 */
public class JFPrincipal1 extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal1
     */
    private ArrayList<CuentaUsuario> usuarios;
    private CuentaUsuario usuario;
    private UsuarioBL LogicaNegocio;
    private Map intentosUsuario;
    
    public JFPrincipal1() throws Exception{
        initComponents();
        LogicaNegocio = new UsuarioBL();
        usuarios = new ArrayList<CuentaUsuario>();
        intentosUsuario = new HashMap();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        helperLabel = new javax.swing.JLabel();
        labelOlvideContra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblUsuario.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblContrasena.setText("Contraseña:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        helperLabel.setText("Para recuperar su contraseña");

        labelOlvideContra.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        labelOlvideContra.setForeground(new java.awt.Color(0, 0, 255));
        labelOlvideContra.setText("aqui");
        labelOlvideContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOlvideContraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblContrasena)
                                        .addComponent(lblUsuario))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(txtUsuario)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnIngresar)
                                    .addGap(77, 77, 77)
                                    .addComponent(btnCancelar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(helperLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelOlvideContra)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helperLabel)
                    .addComponent(labelOlvideContra))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:

        //this.setVisible(false);
        //this.setVisible(false);
        String nombre = txtUsuario.getText();
        String password = new String(jPassword.getPassword());
        
        usuario = LogicaNegocio.buscarUsuarioLogin(nombre);
        
        if(nombre.isEmpty() || password.isEmpty())
            JOptionPane.showMessageDialog(null, "Complete todos los campos por favor", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        else if(usuario==null)
            JOptionPane.showMessageDialog(null, "Usuario no registrado", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        else if(usuario.getBloqueado())
            JOptionPane.showMessageDialog(null, "Usuario bloqueado por multiples ingresos fallidos", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        else if(!password.equals(usuario.getcontrasenha())){
            if(intentosUsuario.containsKey(nombre)){
                if((int)intentosUsuario.get(nombre)==2){
                    LogicaNegocio.bloquearUsuario(usuario.getidUsuario());
                }else{
                    int v = (int)intentosUsuario.get(nombre) + 1;
                    intentosUsuario.put(nombre, v);
                }
            }else{
                intentosUsuario.put(nombre, 1);
            }
            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);   
        }          
        else{
            if(usuario.getpermise().getIdPermiso()==2){
                JFPrincipalVendedor intfzPan = new JFPrincipalVendedor(this,true,usuario);
                intfzPan.setVisible(true);
            }
            else if(usuario.getpermise().getIdPermiso()==3){
                JFPrincipalAdmi intrfSuper = new JFPrincipalAdmi(this,true);
                intrfSuper.setVisible(true);
            }
            else if(usuario.getpermise().getIdPermiso()==1){
                JFPrincipalAdmi intrfSuper = new JFPrincipalAdmi(this,true);
                intrfSuper.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null, "No tiene permiso", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
        }

      
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
        JPasswordField password = new JPasswordField();
    }//GEN-LAST:event_jPasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnIngresar.doClick();
        }
    }//GEN-LAST:event_jPasswordKeyPressed

    
    private void labelOlvideContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOlvideContraMouseClicked
        // TODO add your handling code here:
        JLabel jLabel = new JLabel("Nombre de su usuario");
        JTextField nombreField = new JTextField();
        JPanel panel = new JPanel(new GridLayout(0,1));
        panel.add(jLabel);
        panel.add(nombreField);
        int result = JOptionPane.showConfirmDialog(null, panel, "Recuperacion de contraseña " , JOptionPane.OK_CANCEL_OPTION , JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION){
            if (nombreField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Falta nombre de usuario");
            } else {
               Email recoverEmail = new Email();
                String correo = recoverEmail.getEmailDB(nombreField.getText());
                if (correo == null){
                     JOptionPane.showMessageDialog(null, "Usted no posee cuenta ");
                     return ;
                }
                if (correo.isEmpty() ){
                    JOptionPane.showMessageDialog(null, "Su cuenta no tiene correo ligado a ella ");
                    return;

                }
                
                recoverEmail.prepareConection();
                String contrasena = recoverEmail.getPassword((nombreField.getText()));
                if (contrasena.isEmpty()){
                    return;
                }
                try{
                    recoverEmail.sendEmail("Recuperacion de Contraseña ", "La clave de su usuario es : " + contrasena , correo);
                    JOptionPane.showMessageDialog(this, "Se envio a su correo su contrasena");
                } catch (Exception ex) {
                    System.err.println(ex);
                };

                 // guide https://javaee.github.io/javamail/Gmail // new form for send email 
            }
        }
        
    }//GEN-LAST:event_labelOlvideContraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try{
                    new JFPrincipal1().setVisible(true);
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
                //new JFPrincipal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel helperLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel labelOlvideContra;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
